### PR TITLE
Change port

### PR DESCRIPTION
**Pull request by damwthomas**

### CODE REVIEW

**Comment by zone117x** [comment]
Looks clean, nice job. I'll review this when I get home.

**Comment by zone117x** [comment]
I'm still waiting for some time to review this. BTW how is the API key auth coming along?

**Comment by damwthomas** [comment]
Haven't been able to spent much time on it atm, redoing a part of the house atm so I've been kind of busy and haven't had much time to program.

**Comment by zone117x** [comment]
Tested it out, works well. We should probably put this configuration option and any new ones in its own modal/dialog. But I'll merge it for now.

**Pull request merged**
