### PR TITLE
Add command line arguments to Jackett

### PR DESCRIPTION
**Pull request by sdesbure**
it's always easier in Linux to have command line arguments.
So I added some : 
- `-d Directory` allows to choose the right directory (useful in docker or when user has no directory)
- `-p Port` allows to choose the port and write it in the config
- `-l` allows to listen publicly and write it in the config
- `-L` allows to listen private and write it in the config
- `--verbose` gives you more detail (currently one line but could be done to give DEBUG messages)
- `--help` gives help

### CODE REVIEW

**Comment by Kayomani** [comment]
I agree with the changes but its not mergable in its current state as the code is based off master rather than develop and develop has now been merged.  The server service holds, saves and loads the options you describe.  The command line may be used by windows users too meaning the relevant port reservations as admin need performing (see adminncontroller)

**Comment by sdesbure** [comment]
Hello,
Yeah I saw that :-/
I actually did it start of week but had issues to merge (any changes in a file meant all file changed). I'll look at a revamp this week end!

**Comment by Kayomani** [comment]
Got a few minutes and fixed it for you  :+1:

**Comment by sdesbure** [comment]
Well nice thanks :+1:

**Comment by zone117x** [comment]
Nice job @Kayomani

**Pull request closed without merging**
