### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Venxir**
Changed code to include ChromeUserAgent in requests to alpharatio.

### CODE REVIEW

**Comment by zone117x** [comment]
Nice job! Thanks. Have you tested that the setup button actually works after making changes to an indexer?

**Comment by Venxir** [comment]
Just fixed it for AlphaRatio as a test. I need a proper way to reset the cookies which were stored. Probably make something new in the IndexManager to accomodate a reset cookies in json+cookcontainer.

**Comment by zone117x** [comment]
Would you be interested in becoming a maintainer for this repo? I need help uploading new builds to the releases page.

**Comment by Venxir** [comment]
Hello Matthew,

I don’t have much time and also don’t have access to any torrentsite except alphaRatio. Which makes debugging quite nasty ;).

Other than that, it sounds like fun.

Regards,

Maikel

Van: Matthew Little [mailto:notifications@github.com] 
Verzonden: woensdag 24 juni 2015 22:35
Aan: zone117x/Jackett
CC: Venxir
Onderwerp: Re: [Jackett] Various fixes (#68)

Would you be interested in becoming a maintainer for this repo? I need help uploading new builds to the releases page.

**Pull request merged**
